// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.example.grpc.server.grpcserver.employee;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.employee.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.grpc.server.grpcserver.employee.ProtoEmployee employee = 1;</code>
   */
  boolean hasEmployee();
  /**
   * <code>.com.example.grpc.server.grpcserver.employee.ProtoEmployee employee = 1;</code>
   */
  com.example.grpc.server.grpcserver.employee.ProtoEmployee getEmployee();
  /**
   * <code>.com.example.grpc.server.grpcserver.employee.ProtoEmployee employee = 1;</code>
   */
  com.example.grpc.server.grpcserver.employee.ProtoEmployeeOrBuilder getEmployeeOrBuilder();
}
