// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hookah.proto

package com.example.grpc.server.grpcserver.hookah;

/**
 * Protobuf type {@code com.example.grpc.server.grpcserver.hookah.GetResponse}
 */
public  final class GetResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.server.grpcserver.hookah.GetResponse)
    GetResponseOrBuilder {
  // Use GetResponse.newBuilder() to construct.
  private GetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetResponse() {
    hookahs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GetResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              hookahs_ = new java.util.ArrayList<com.example.grpc.server.grpcserver.hookah.ProtoHookah>();
              mutable_bitField0_ |= 0x00000001;
            }
            hookahs_.add(
                input.readMessage(com.example.grpc.server.grpcserver.hookah.ProtoHookah.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        hookahs_ = java.util.Collections.unmodifiableList(hookahs_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.server.grpcserver.hookah.Hookah.internal_static_com_example_grpc_server_grpcserver_hookah_GetResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.server.grpcserver.hookah.Hookah.internal_static_com_example_grpc_server_grpcserver_hookah_GetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.server.grpcserver.hookah.GetResponse.class, com.example.grpc.server.grpcserver.hookah.GetResponse.Builder.class);
  }

  public static final int HOOKAHS_FIELD_NUMBER = 1;
  private java.util.List<com.example.grpc.server.grpcserver.hookah.ProtoHookah> hookahs_;
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
   */
  public java.util.List<com.example.grpc.server.grpcserver.hookah.ProtoHookah> getHookahsList() {
    return hookahs_;
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
   */
  public java.util.List<? extends com.example.grpc.server.grpcserver.hookah.ProtoHookahOrBuilder> 
      getHookahsOrBuilderList() {
    return hookahs_;
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
   */
  public int getHookahsCount() {
    return hookahs_.size();
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
   */
  public com.example.grpc.server.grpcserver.hookah.ProtoHookah getHookahs(int index) {
    return hookahs_.get(index);
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
   */
  public com.example.grpc.server.grpcserver.hookah.ProtoHookahOrBuilder getHookahsOrBuilder(
      int index) {
    return hookahs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < hookahs_.size(); i++) {
      output.writeMessage(1, hookahs_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < hookahs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, hookahs_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.server.grpcserver.hookah.GetResponse)) {
      return super.equals(obj);
    }
    com.example.grpc.server.grpcserver.hookah.GetResponse other = (com.example.grpc.server.grpcserver.hookah.GetResponse) obj;

    boolean result = true;
    result = result && getHookahsList()
        .equals(other.getHookahsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getHookahsCount() > 0) {
      hash = (37 * hash) + HOOKAHS_FIELD_NUMBER;
      hash = (53 * hash) + getHookahsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.server.grpcserver.hookah.GetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.hookah.GetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.hookah.GetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.hookah.GetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.hookah.GetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.hookah.GetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.hookah.GetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.hookah.GetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.hookah.GetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.hookah.GetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.hookah.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.hookah.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.server.grpcserver.hookah.GetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.server.grpcserver.hookah.GetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.server.grpcserver.hookah.GetResponse)
      com.example.grpc.server.grpcserver.hookah.GetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.server.grpcserver.hookah.Hookah.internal_static_com_example_grpc_server_grpcserver_hookah_GetResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.server.grpcserver.hookah.Hookah.internal_static_com_example_grpc_server_grpcserver_hookah_GetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.server.grpcserver.hookah.GetResponse.class, com.example.grpc.server.grpcserver.hookah.GetResponse.Builder.class);
    }

    // Construct using com.example.grpc.server.grpcserver.hookah.GetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHookahsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (hookahsBuilder_ == null) {
        hookahs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        hookahsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.server.grpcserver.hookah.Hookah.internal_static_com_example_grpc_server_grpcserver_hookah_GetResponse_descriptor;
    }

    public com.example.grpc.server.grpcserver.hookah.GetResponse getDefaultInstanceForType() {
      return com.example.grpc.server.grpcserver.hookah.GetResponse.getDefaultInstance();
    }

    public com.example.grpc.server.grpcserver.hookah.GetResponse build() {
      com.example.grpc.server.grpcserver.hookah.GetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.example.grpc.server.grpcserver.hookah.GetResponse buildPartial() {
      com.example.grpc.server.grpcserver.hookah.GetResponse result = new com.example.grpc.server.grpcserver.hookah.GetResponse(this);
      int from_bitField0_ = bitField0_;
      if (hookahsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          hookahs_ = java.util.Collections.unmodifiableList(hookahs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.hookahs_ = hookahs_;
      } else {
        result.hookahs_ = hookahsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.server.grpcserver.hookah.GetResponse) {
        return mergeFrom((com.example.grpc.server.grpcserver.hookah.GetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.server.grpcserver.hookah.GetResponse other) {
      if (other == com.example.grpc.server.grpcserver.hookah.GetResponse.getDefaultInstance()) return this;
      if (hookahsBuilder_ == null) {
        if (!other.hookahs_.isEmpty()) {
          if (hookahs_.isEmpty()) {
            hookahs_ = other.hookahs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHookahsIsMutable();
            hookahs_.addAll(other.hookahs_);
          }
          onChanged();
        }
      } else {
        if (!other.hookahs_.isEmpty()) {
          if (hookahsBuilder_.isEmpty()) {
            hookahsBuilder_.dispose();
            hookahsBuilder_ = null;
            hookahs_ = other.hookahs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            hookahsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHookahsFieldBuilder() : null;
          } else {
            hookahsBuilder_.addAllMessages(other.hookahs_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.server.grpcserver.hookah.GetResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.server.grpcserver.hookah.GetResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.grpc.server.grpcserver.hookah.ProtoHookah> hookahs_ =
      java.util.Collections.emptyList();
    private void ensureHookahsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        hookahs_ = new java.util.ArrayList<com.example.grpc.server.grpcserver.hookah.ProtoHookah>(hookahs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.server.grpcserver.hookah.ProtoHookah, com.example.grpc.server.grpcserver.hookah.ProtoHookah.Builder, com.example.grpc.server.grpcserver.hookah.ProtoHookahOrBuilder> hookahsBuilder_;

    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public java.util.List<com.example.grpc.server.grpcserver.hookah.ProtoHookah> getHookahsList() {
      if (hookahsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(hookahs_);
      } else {
        return hookahsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public int getHookahsCount() {
      if (hookahsBuilder_ == null) {
        return hookahs_.size();
      } else {
        return hookahsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public com.example.grpc.server.grpcserver.hookah.ProtoHookah getHookahs(int index) {
      if (hookahsBuilder_ == null) {
        return hookahs_.get(index);
      } else {
        return hookahsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public Builder setHookahs(
        int index, com.example.grpc.server.grpcserver.hookah.ProtoHookah value) {
      if (hookahsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHookahsIsMutable();
        hookahs_.set(index, value);
        onChanged();
      } else {
        hookahsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public Builder setHookahs(
        int index, com.example.grpc.server.grpcserver.hookah.ProtoHookah.Builder builderForValue) {
      if (hookahsBuilder_ == null) {
        ensureHookahsIsMutable();
        hookahs_.set(index, builderForValue.build());
        onChanged();
      } else {
        hookahsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public Builder addHookahs(com.example.grpc.server.grpcserver.hookah.ProtoHookah value) {
      if (hookahsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHookahsIsMutable();
        hookahs_.add(value);
        onChanged();
      } else {
        hookahsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public Builder addHookahs(
        int index, com.example.grpc.server.grpcserver.hookah.ProtoHookah value) {
      if (hookahsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHookahsIsMutable();
        hookahs_.add(index, value);
        onChanged();
      } else {
        hookahsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public Builder addHookahs(
        com.example.grpc.server.grpcserver.hookah.ProtoHookah.Builder builderForValue) {
      if (hookahsBuilder_ == null) {
        ensureHookahsIsMutable();
        hookahs_.add(builderForValue.build());
        onChanged();
      } else {
        hookahsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public Builder addHookahs(
        int index, com.example.grpc.server.grpcserver.hookah.ProtoHookah.Builder builderForValue) {
      if (hookahsBuilder_ == null) {
        ensureHookahsIsMutable();
        hookahs_.add(index, builderForValue.build());
        onChanged();
      } else {
        hookahsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public Builder addAllHookahs(
        java.lang.Iterable<? extends com.example.grpc.server.grpcserver.hookah.ProtoHookah> values) {
      if (hookahsBuilder_ == null) {
        ensureHookahsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hookahs_);
        onChanged();
      } else {
        hookahsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public Builder clearHookahs() {
      if (hookahsBuilder_ == null) {
        hookahs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        hookahsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public Builder removeHookahs(int index) {
      if (hookahsBuilder_ == null) {
        ensureHookahsIsMutable();
        hookahs_.remove(index);
        onChanged();
      } else {
        hookahsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public com.example.grpc.server.grpcserver.hookah.ProtoHookah.Builder getHookahsBuilder(
        int index) {
      return getHookahsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public com.example.grpc.server.grpcserver.hookah.ProtoHookahOrBuilder getHookahsOrBuilder(
        int index) {
      if (hookahsBuilder_ == null) {
        return hookahs_.get(index);  } else {
        return hookahsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public java.util.List<? extends com.example.grpc.server.grpcserver.hookah.ProtoHookahOrBuilder> 
         getHookahsOrBuilderList() {
      if (hookahsBuilder_ != null) {
        return hookahsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(hookahs_);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public com.example.grpc.server.grpcserver.hookah.ProtoHookah.Builder addHookahsBuilder() {
      return getHookahsFieldBuilder().addBuilder(
          com.example.grpc.server.grpcserver.hookah.ProtoHookah.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public com.example.grpc.server.grpcserver.hookah.ProtoHookah.Builder addHookahsBuilder(
        int index) {
      return getHookahsFieldBuilder().addBuilder(
          index, com.example.grpc.server.grpcserver.hookah.ProtoHookah.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
     */
    public java.util.List<com.example.grpc.server.grpcserver.hookah.ProtoHookah.Builder> 
         getHookahsBuilderList() {
      return getHookahsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.server.grpcserver.hookah.ProtoHookah, com.example.grpc.server.grpcserver.hookah.ProtoHookah.Builder, com.example.grpc.server.grpcserver.hookah.ProtoHookahOrBuilder> 
        getHookahsFieldBuilder() {
      if (hookahsBuilder_ == null) {
        hookahsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.grpc.server.grpcserver.hookah.ProtoHookah, com.example.grpc.server.grpcserver.hookah.ProtoHookah.Builder, com.example.grpc.server.grpcserver.hookah.ProtoHookahOrBuilder>(
                hookahs_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        hookahs_ = null;
      }
      return hookahsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.server.grpcserver.hookah.GetResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.server.grpcserver.hookah.GetResponse)
  private static final com.example.grpc.server.grpcserver.hookah.GetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.server.grpcserver.hookah.GetResponse();
  }

  public static com.example.grpc.server.grpcserver.hookah.GetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetResponse>() {
    public GetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetResponse> getParserForType() {
    return PARSER;
  }

  public com.example.grpc.server.grpcserver.hookah.GetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

