// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hookah.proto

package com.example.grpc.server.grpcserver.hookah;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.hookah.GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
   */
  java.util.List<com.example.grpc.server.grpcserver.hookah.ProtoHookah> 
      getHookahsList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
   */
  com.example.grpc.server.grpcserver.hookah.ProtoHookah getHookahs(int index);
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
   */
  int getHookahsCount();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
   */
  java.util.List<? extends com.example.grpc.server.grpcserver.hookah.ProtoHookahOrBuilder> 
      getHookahsOrBuilderList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.hookah.ProtoHookah hookahs = 1;</code>
   */
  com.example.grpc.server.grpcserver.hookah.ProtoHookahOrBuilder getHookahsOrBuilder(
      int index);
}
