// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hookah.proto

package com.example.grpc.server.grpcserver.hookah;

public interface ProtoHookahOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.hookah.ProtoHookah)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string producer = 1;</code>
   */
  java.lang.String getProducer();
  /**
   * <code>string producer = 1;</code>
   */
  com.google.protobuf.ByteString
      getProducerBytes();

  /**
   * <code>string material = 2;</code>
   */
  java.lang.String getMaterial();
  /**
   * <code>string material = 2;</code>
   */
  com.google.protobuf.ByteString
      getMaterialBytes();

  /**
   * <code>string size = 3;</code>
   */
  java.lang.String getSize();
  /**
   * <code>string size = 3;</code>
   */
  com.google.protobuf.ByteString
      getSizeBytes();

  /**
   * <code>int32 price = 4;</code>
   */
  int getPrice();
}
