// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tobakko.proto

package com.example.grpc.server.grpcserver.tobakko;

/**
 * Protobuf type {@code com.example.grpc.server.grpcserver.tobakko.GetResponse}
 */
public  final class GetResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.server.grpcserver.tobakko.GetResponse)
    GetResponseOrBuilder {
  // Use GetResponse.newBuilder() to construct.
  private GetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetResponse() {
    tobakkos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GetResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              tobakkos_ = new java.util.ArrayList<com.example.grpc.server.grpcserver.tobakko.ProtoTobakko>();
              mutable_bitField0_ |= 0x00000001;
            }
            tobakkos_.add(
                input.readMessage(com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        tobakkos_ = java.util.Collections.unmodifiableList(tobakkos_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.server.grpcserver.tobakko.Tobakko.internal_static_com_example_grpc_server_grpcserver_tobakko_GetResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.server.grpcserver.tobakko.Tobakko.internal_static_com_example_grpc_server_grpcserver_tobakko_GetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.server.grpcserver.tobakko.GetResponse.class, com.example.grpc.server.grpcserver.tobakko.GetResponse.Builder.class);
  }

  public static final int TOBAKKOS_FIELD_NUMBER = 1;
  private java.util.List<com.example.grpc.server.grpcserver.tobakko.ProtoTobakko> tobakkos_;
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
   */
  public java.util.List<com.example.grpc.server.grpcserver.tobakko.ProtoTobakko> getTobakkosList() {
    return tobakkos_;
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
   */
  public java.util.List<? extends com.example.grpc.server.grpcserver.tobakko.ProtoTobakkoOrBuilder> 
      getTobakkosOrBuilderList() {
    return tobakkos_;
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
   */
  public int getTobakkosCount() {
    return tobakkos_.size();
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
   */
  public com.example.grpc.server.grpcserver.tobakko.ProtoTobakko getTobakkos(int index) {
    return tobakkos_.get(index);
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
   */
  public com.example.grpc.server.grpcserver.tobakko.ProtoTobakkoOrBuilder getTobakkosOrBuilder(
      int index) {
    return tobakkos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tobakkos_.size(); i++) {
      output.writeMessage(1, tobakkos_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < tobakkos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, tobakkos_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.server.grpcserver.tobakko.GetResponse)) {
      return super.equals(obj);
    }
    com.example.grpc.server.grpcserver.tobakko.GetResponse other = (com.example.grpc.server.grpcserver.tobakko.GetResponse) obj;

    boolean result = true;
    result = result && getTobakkosList()
        .equals(other.getTobakkosList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTobakkosCount() > 0) {
      hash = (37 * hash) + TOBAKKOS_FIELD_NUMBER;
      hash = (53 * hash) + getTobakkosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.server.grpcserver.tobakko.GetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.tobakko.GetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.tobakko.GetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.tobakko.GetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.tobakko.GetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.tobakko.GetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.tobakko.GetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.tobakko.GetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.tobakko.GetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.tobakko.GetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.tobakko.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.tobakko.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.server.grpcserver.tobakko.GetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.server.grpcserver.tobakko.GetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.server.grpcserver.tobakko.GetResponse)
      com.example.grpc.server.grpcserver.tobakko.GetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.server.grpcserver.tobakko.Tobakko.internal_static_com_example_grpc_server_grpcserver_tobakko_GetResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.server.grpcserver.tobakko.Tobakko.internal_static_com_example_grpc_server_grpcserver_tobakko_GetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.server.grpcserver.tobakko.GetResponse.class, com.example.grpc.server.grpcserver.tobakko.GetResponse.Builder.class);
    }

    // Construct using com.example.grpc.server.grpcserver.tobakko.GetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTobakkosFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (tobakkosBuilder_ == null) {
        tobakkos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        tobakkosBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.server.grpcserver.tobakko.Tobakko.internal_static_com_example_grpc_server_grpcserver_tobakko_GetResponse_descriptor;
    }

    public com.example.grpc.server.grpcserver.tobakko.GetResponse getDefaultInstanceForType() {
      return com.example.grpc.server.grpcserver.tobakko.GetResponse.getDefaultInstance();
    }

    public com.example.grpc.server.grpcserver.tobakko.GetResponse build() {
      com.example.grpc.server.grpcserver.tobakko.GetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.example.grpc.server.grpcserver.tobakko.GetResponse buildPartial() {
      com.example.grpc.server.grpcserver.tobakko.GetResponse result = new com.example.grpc.server.grpcserver.tobakko.GetResponse(this);
      int from_bitField0_ = bitField0_;
      if (tobakkosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          tobakkos_ = java.util.Collections.unmodifiableList(tobakkos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tobakkos_ = tobakkos_;
      } else {
        result.tobakkos_ = tobakkosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.server.grpcserver.tobakko.GetResponse) {
        return mergeFrom((com.example.grpc.server.grpcserver.tobakko.GetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.server.grpcserver.tobakko.GetResponse other) {
      if (other == com.example.grpc.server.grpcserver.tobakko.GetResponse.getDefaultInstance()) return this;
      if (tobakkosBuilder_ == null) {
        if (!other.tobakkos_.isEmpty()) {
          if (tobakkos_.isEmpty()) {
            tobakkos_ = other.tobakkos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTobakkosIsMutable();
            tobakkos_.addAll(other.tobakkos_);
          }
          onChanged();
        }
      } else {
        if (!other.tobakkos_.isEmpty()) {
          if (tobakkosBuilder_.isEmpty()) {
            tobakkosBuilder_.dispose();
            tobakkosBuilder_ = null;
            tobakkos_ = other.tobakkos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            tobakkosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTobakkosFieldBuilder() : null;
          } else {
            tobakkosBuilder_.addAllMessages(other.tobakkos_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.server.grpcserver.tobakko.GetResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.server.grpcserver.tobakko.GetResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.grpc.server.grpcserver.tobakko.ProtoTobakko> tobakkos_ =
      java.util.Collections.emptyList();
    private void ensureTobakkosIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        tobakkos_ = new java.util.ArrayList<com.example.grpc.server.grpcserver.tobakko.ProtoTobakko>(tobakkos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.server.grpcserver.tobakko.ProtoTobakko, com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.Builder, com.example.grpc.server.grpcserver.tobakko.ProtoTobakkoOrBuilder> tobakkosBuilder_;

    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public java.util.List<com.example.grpc.server.grpcserver.tobakko.ProtoTobakko> getTobakkosList() {
      if (tobakkosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tobakkos_);
      } else {
        return tobakkosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public int getTobakkosCount() {
      if (tobakkosBuilder_ == null) {
        return tobakkos_.size();
      } else {
        return tobakkosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public com.example.grpc.server.grpcserver.tobakko.ProtoTobakko getTobakkos(int index) {
      if (tobakkosBuilder_ == null) {
        return tobakkos_.get(index);
      } else {
        return tobakkosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public Builder setTobakkos(
        int index, com.example.grpc.server.grpcserver.tobakko.ProtoTobakko value) {
      if (tobakkosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTobakkosIsMutable();
        tobakkos_.set(index, value);
        onChanged();
      } else {
        tobakkosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public Builder setTobakkos(
        int index, com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.Builder builderForValue) {
      if (tobakkosBuilder_ == null) {
        ensureTobakkosIsMutable();
        tobakkos_.set(index, builderForValue.build());
        onChanged();
      } else {
        tobakkosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public Builder addTobakkos(com.example.grpc.server.grpcserver.tobakko.ProtoTobakko value) {
      if (tobakkosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTobakkosIsMutable();
        tobakkos_.add(value);
        onChanged();
      } else {
        tobakkosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public Builder addTobakkos(
        int index, com.example.grpc.server.grpcserver.tobakko.ProtoTobakko value) {
      if (tobakkosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTobakkosIsMutable();
        tobakkos_.add(index, value);
        onChanged();
      } else {
        tobakkosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public Builder addTobakkos(
        com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.Builder builderForValue) {
      if (tobakkosBuilder_ == null) {
        ensureTobakkosIsMutable();
        tobakkos_.add(builderForValue.build());
        onChanged();
      } else {
        tobakkosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public Builder addTobakkos(
        int index, com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.Builder builderForValue) {
      if (tobakkosBuilder_ == null) {
        ensureTobakkosIsMutable();
        tobakkos_.add(index, builderForValue.build());
        onChanged();
      } else {
        tobakkosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public Builder addAllTobakkos(
        java.lang.Iterable<? extends com.example.grpc.server.grpcserver.tobakko.ProtoTobakko> values) {
      if (tobakkosBuilder_ == null) {
        ensureTobakkosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tobakkos_);
        onChanged();
      } else {
        tobakkosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public Builder clearTobakkos() {
      if (tobakkosBuilder_ == null) {
        tobakkos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        tobakkosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public Builder removeTobakkos(int index) {
      if (tobakkosBuilder_ == null) {
        ensureTobakkosIsMutable();
        tobakkos_.remove(index);
        onChanged();
      } else {
        tobakkosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.Builder getTobakkosBuilder(
        int index) {
      return getTobakkosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public com.example.grpc.server.grpcserver.tobakko.ProtoTobakkoOrBuilder getTobakkosOrBuilder(
        int index) {
      if (tobakkosBuilder_ == null) {
        return tobakkos_.get(index);  } else {
        return tobakkosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public java.util.List<? extends com.example.grpc.server.grpcserver.tobakko.ProtoTobakkoOrBuilder> 
         getTobakkosOrBuilderList() {
      if (tobakkosBuilder_ != null) {
        return tobakkosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tobakkos_);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.Builder addTobakkosBuilder() {
      return getTobakkosFieldBuilder().addBuilder(
          com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.Builder addTobakkosBuilder(
        int index) {
      return getTobakkosFieldBuilder().addBuilder(
          index, com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
     */
    public java.util.List<com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.Builder> 
         getTobakkosBuilderList() {
      return getTobakkosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.server.grpcserver.tobakko.ProtoTobakko, com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.Builder, com.example.grpc.server.grpcserver.tobakko.ProtoTobakkoOrBuilder> 
        getTobakkosFieldBuilder() {
      if (tobakkosBuilder_ == null) {
        tobakkosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.grpc.server.grpcserver.tobakko.ProtoTobakko, com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.Builder, com.example.grpc.server.grpcserver.tobakko.ProtoTobakkoOrBuilder>(
                tobakkos_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        tobakkos_ = null;
      }
      return tobakkosBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.server.grpcserver.tobakko.GetResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.server.grpcserver.tobakko.GetResponse)
  private static final com.example.grpc.server.grpcserver.tobakko.GetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.server.grpcserver.tobakko.GetResponse();
  }

  public static com.example.grpc.server.grpcserver.tobakko.GetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetResponse>() {
    public GetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetResponse> getParserForType() {
    return PARSER;
  }

  public com.example.grpc.server.grpcserver.tobakko.GetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

