// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tobakko.proto

package com.example.grpc.server.grpcserver.tobakko;

/**
 * Protobuf type {@code com.example.grpc.server.grpcserver.tobakko.ProtoTobakko}
 */
public  final class ProtoTobakko extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.server.grpcserver.tobakko.ProtoTobakko)
    ProtoTobakkoOrBuilder {
  // Use ProtoTobakko.newBuilder() to construct.
  private ProtoTobakko(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoTobakko() {
    firm_ = "";
    taste_ = "";
    strength_ = "";
    price_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ProtoTobakko(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            firm_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            taste_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            strength_ = s;
            break;
          }
          case 32: {

            price_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.server.grpcserver.tobakko.Tobakko.internal_static_com_example_grpc_server_grpcserver_tobakko_ProtoTobakko_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.server.grpcserver.tobakko.Tobakko.internal_static_com_example_grpc_server_grpcserver_tobakko_ProtoTobakko_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.class, com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.Builder.class);
  }

  public static final int FIRM_FIELD_NUMBER = 1;
  private volatile java.lang.Object firm_;
  /**
   * <code>string firm = 1;</code>
   */
  public java.lang.String getFirm() {
    java.lang.Object ref = firm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firm_ = s;
      return s;
    }
  }
  /**
   * <code>string firm = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFirmBytes() {
    java.lang.Object ref = firm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASTE_FIELD_NUMBER = 2;
  private volatile java.lang.Object taste_;
  /**
   * <code>string taste = 2;</code>
   */
  public java.lang.String getTaste() {
    java.lang.Object ref = taste_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taste_ = s;
      return s;
    }
  }
  /**
   * <code>string taste = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTasteBytes() {
    java.lang.Object ref = taste_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taste_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRENGTH_FIELD_NUMBER = 3;
  private volatile java.lang.Object strength_;
  /**
   * <code>string strength = 3;</code>
   */
  public java.lang.String getStrength() {
    java.lang.Object ref = strength_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      strength_ = s;
      return s;
    }
  }
  /**
   * <code>string strength = 3;</code>
   */
  public com.google.protobuf.ByteString
      getStrengthBytes() {
    java.lang.Object ref = strength_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      strength_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 4;
  private int price_;
  /**
   * <code>int32 price = 4;</code>
   */
  public int getPrice() {
    return price_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFirmBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firm_);
    }
    if (!getTasteBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taste_);
    }
    if (!getStrengthBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, strength_);
    }
    if (price_ != 0) {
      output.writeInt32(4, price_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFirmBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firm_);
    }
    if (!getTasteBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taste_);
    }
    if (!getStrengthBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, strength_);
    }
    if (price_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, price_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.server.grpcserver.tobakko.ProtoTobakko)) {
      return super.equals(obj);
    }
    com.example.grpc.server.grpcserver.tobakko.ProtoTobakko other = (com.example.grpc.server.grpcserver.tobakko.ProtoTobakko) obj;

    boolean result = true;
    result = result && getFirm()
        .equals(other.getFirm());
    result = result && getTaste()
        .equals(other.getTaste());
    result = result && getStrength()
        .equals(other.getStrength());
    result = result && (getPrice()
        == other.getPrice());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FIRM_FIELD_NUMBER;
    hash = (53 * hash) + getFirm().hashCode();
    hash = (37 * hash) + TASTE_FIELD_NUMBER;
    hash = (53 * hash) + getTaste().hashCode();
    hash = (37 * hash) + STRENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getStrength().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getPrice();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.server.grpcserver.tobakko.ProtoTobakko parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.tobakko.ProtoTobakko parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.tobakko.ProtoTobakko parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.tobakko.ProtoTobakko parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.tobakko.ProtoTobakko parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.tobakko.ProtoTobakko parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.tobakko.ProtoTobakko parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.tobakko.ProtoTobakko parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.tobakko.ProtoTobakko parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.tobakko.ProtoTobakko parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.tobakko.ProtoTobakko parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.tobakko.ProtoTobakko parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.server.grpcserver.tobakko.ProtoTobakko prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.server.grpcserver.tobakko.ProtoTobakko}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.server.grpcserver.tobakko.ProtoTobakko)
      com.example.grpc.server.grpcserver.tobakko.ProtoTobakkoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.server.grpcserver.tobakko.Tobakko.internal_static_com_example_grpc_server_grpcserver_tobakko_ProtoTobakko_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.server.grpcserver.tobakko.Tobakko.internal_static_com_example_grpc_server_grpcserver_tobakko_ProtoTobakko_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.class, com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.Builder.class);
    }

    // Construct using com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      firm_ = "";

      taste_ = "";

      strength_ = "";

      price_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.server.grpcserver.tobakko.Tobakko.internal_static_com_example_grpc_server_grpcserver_tobakko_ProtoTobakko_descriptor;
    }

    public com.example.grpc.server.grpcserver.tobakko.ProtoTobakko getDefaultInstanceForType() {
      return com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.getDefaultInstance();
    }

    public com.example.grpc.server.grpcserver.tobakko.ProtoTobakko build() {
      com.example.grpc.server.grpcserver.tobakko.ProtoTobakko result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.example.grpc.server.grpcserver.tobakko.ProtoTobakko buildPartial() {
      com.example.grpc.server.grpcserver.tobakko.ProtoTobakko result = new com.example.grpc.server.grpcserver.tobakko.ProtoTobakko(this);
      result.firm_ = firm_;
      result.taste_ = taste_;
      result.strength_ = strength_;
      result.price_ = price_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.server.grpcserver.tobakko.ProtoTobakko) {
        return mergeFrom((com.example.grpc.server.grpcserver.tobakko.ProtoTobakko)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.server.grpcserver.tobakko.ProtoTobakko other) {
      if (other == com.example.grpc.server.grpcserver.tobakko.ProtoTobakko.getDefaultInstance()) return this;
      if (!other.getFirm().isEmpty()) {
        firm_ = other.firm_;
        onChanged();
      }
      if (!other.getTaste().isEmpty()) {
        taste_ = other.taste_;
        onChanged();
      }
      if (!other.getStrength().isEmpty()) {
        strength_ = other.strength_;
        onChanged();
      }
      if (other.getPrice() != 0) {
        setPrice(other.getPrice());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.server.grpcserver.tobakko.ProtoTobakko parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.server.grpcserver.tobakko.ProtoTobakko) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object firm_ = "";
    /**
     * <code>string firm = 1;</code>
     */
    public java.lang.String getFirm() {
      java.lang.Object ref = firm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string firm = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirmBytes() {
      java.lang.Object ref = firm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string firm = 1;</code>
     */
    public Builder setFirm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      firm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string firm = 1;</code>
     */
    public Builder clearFirm() {
      
      firm_ = getDefaultInstance().getFirm();
      onChanged();
      return this;
    }
    /**
     * <code>string firm = 1;</code>
     */
    public Builder setFirmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      firm_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object taste_ = "";
    /**
     * <code>string taste = 2;</code>
     */
    public java.lang.String getTaste() {
      java.lang.Object ref = taste_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taste_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string taste = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTasteBytes() {
      java.lang.Object ref = taste_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taste_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string taste = 2;</code>
     */
    public Builder setTaste(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taste_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string taste = 2;</code>
     */
    public Builder clearTaste() {
      
      taste_ = getDefaultInstance().getTaste();
      onChanged();
      return this;
    }
    /**
     * <code>string taste = 2;</code>
     */
    public Builder setTasteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taste_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object strength_ = "";
    /**
     * <code>string strength = 3;</code>
     */
    public java.lang.String getStrength() {
      java.lang.Object ref = strength_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        strength_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string strength = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStrengthBytes() {
      java.lang.Object ref = strength_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strength_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string strength = 3;</code>
     */
    public Builder setStrength(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      strength_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string strength = 3;</code>
     */
    public Builder clearStrength() {
      
      strength_ = getDefaultInstance().getStrength();
      onChanged();
      return this;
    }
    /**
     * <code>string strength = 3;</code>
     */
    public Builder setStrengthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      strength_ = value;
      onChanged();
      return this;
    }

    private int price_ ;
    /**
     * <code>int32 price = 4;</code>
     */
    public int getPrice() {
      return price_;
    }
    /**
     * <code>int32 price = 4;</code>
     */
    public Builder setPrice(int value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 price = 4;</code>
     */
    public Builder clearPrice() {
      
      price_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.server.grpcserver.tobakko.ProtoTobakko)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.server.grpcserver.tobakko.ProtoTobakko)
  private static final com.example.grpc.server.grpcserver.tobakko.ProtoTobakko DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.server.grpcserver.tobakko.ProtoTobakko();
  }

  public static com.example.grpc.server.grpcserver.tobakko.ProtoTobakko getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoTobakko>
      PARSER = new com.google.protobuf.AbstractParser<ProtoTobakko>() {
    public ProtoTobakko parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoTobakko(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoTobakko> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoTobakko> getParserForType() {
    return PARSER;
  }

  public com.example.grpc.server.grpcserver.tobakko.ProtoTobakko getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

