// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hookah.proto

package com.example.grpc.server.grpcserver.hookah;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.hookah.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.grpc.server.grpcserver.hookah.ProtoHookah hookah = 1;</code>
   */
  boolean hasHookah();
  /**
   * <code>.com.example.grpc.server.grpcserver.hookah.ProtoHookah hookah = 1;</code>
   */
  com.example.grpc.server.grpcserver.hookah.ProtoHookah getHookah();
  /**
   * <code>.com.example.grpc.server.grpcserver.hookah.ProtoHookah hookah = 1;</code>
   */
  com.example.grpc.server.grpcserver.hookah.ProtoHookahOrBuilder getHookahOrBuilder();
}
