// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hookah.proto

package com.example.grpc.server.grpcserver.hookah;

public interface DeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.hookah.DeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hookah_id = 1;</code>
   */
  java.lang.String getHookahId();
  /**
   * <code>string hookah_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getHookahIdBytes();

  /**
   * <code>string payment_id = 2;</code>
   */
  java.lang.String getPaymentId();
  /**
   * <code>string payment_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getPaymentIdBytes();
}
