// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hookah.proto

package com.example.grpc.server.grpcserver.hookah;

public interface DeleteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.hookah.DeleteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string report = 1;</code>
   */
  java.lang.String getReport();
  /**
   * <code>string report = 1;</code>
   */
  com.google.protobuf.ByteString
      getReportBytes();
}
