// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hookah.proto

package com.example.grpc.server.grpcserver.hookah;

/**
 * Protobuf type {@code com.example.grpc.server.grpcserver.hookah.ProtoHookah}
 */
public  final class ProtoHookah extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.server.grpcserver.hookah.ProtoHookah)
    ProtoHookahOrBuilder {
  // Use ProtoHookah.newBuilder() to construct.
  private ProtoHookah(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoHookah() {
    producer_ = "";
    material_ = "";
    size_ = "";
    price_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ProtoHookah(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            producer_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            material_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            size_ = s;
            break;
          }
          case 32: {

            price_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.server.grpcserver.hookah.Hookah.internal_static_com_example_grpc_server_grpcserver_hookah_ProtoHookah_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.server.grpcserver.hookah.Hookah.internal_static_com_example_grpc_server_grpcserver_hookah_ProtoHookah_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.server.grpcserver.hookah.ProtoHookah.class, com.example.grpc.server.grpcserver.hookah.ProtoHookah.Builder.class);
  }

  public static final int PRODUCER_FIELD_NUMBER = 1;
  private volatile java.lang.Object producer_;
  /**
   * <code>string producer = 1;</code>
   */
  public java.lang.String getProducer() {
    java.lang.Object ref = producer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      producer_ = s;
      return s;
    }
  }
  /**
   * <code>string producer = 1;</code>
   */
  public com.google.protobuf.ByteString
      getProducerBytes() {
    java.lang.Object ref = producer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      producer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MATERIAL_FIELD_NUMBER = 2;
  private volatile java.lang.Object material_;
  /**
   * <code>string material = 2;</code>
   */
  public java.lang.String getMaterial() {
    java.lang.Object ref = material_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      material_ = s;
      return s;
    }
  }
  /**
   * <code>string material = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMaterialBytes() {
    java.lang.Object ref = material_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      material_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIZE_FIELD_NUMBER = 3;
  private volatile java.lang.Object size_;
  /**
   * <code>string size = 3;</code>
   */
  public java.lang.String getSize() {
    java.lang.Object ref = size_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      size_ = s;
      return s;
    }
  }
  /**
   * <code>string size = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSizeBytes() {
    java.lang.Object ref = size_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      size_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 4;
  private int price_;
  /**
   * <code>int32 price = 4;</code>
   */
  public int getPrice() {
    return price_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getProducerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, producer_);
    }
    if (!getMaterialBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, material_);
    }
    if (!getSizeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, size_);
    }
    if (price_ != 0) {
      output.writeInt32(4, price_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getProducerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, producer_);
    }
    if (!getMaterialBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, material_);
    }
    if (!getSizeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, size_);
    }
    if (price_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, price_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.server.grpcserver.hookah.ProtoHookah)) {
      return super.equals(obj);
    }
    com.example.grpc.server.grpcserver.hookah.ProtoHookah other = (com.example.grpc.server.grpcserver.hookah.ProtoHookah) obj;

    boolean result = true;
    result = result && getProducer()
        .equals(other.getProducer());
    result = result && getMaterial()
        .equals(other.getMaterial());
    result = result && getSize()
        .equals(other.getSize());
    result = result && (getPrice()
        == other.getPrice());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRODUCER_FIELD_NUMBER;
    hash = (53 * hash) + getProducer().hashCode();
    hash = (37 * hash) + MATERIAL_FIELD_NUMBER;
    hash = (53 * hash) + getMaterial().hashCode();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getPrice();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.server.grpcserver.hookah.ProtoHookah parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.hookah.ProtoHookah parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.hookah.ProtoHookah parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.hookah.ProtoHookah parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.hookah.ProtoHookah parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.hookah.ProtoHookah parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.hookah.ProtoHookah parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.hookah.ProtoHookah parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.hookah.ProtoHookah parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.hookah.ProtoHookah parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.hookah.ProtoHookah parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.hookah.ProtoHookah parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.server.grpcserver.hookah.ProtoHookah prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.server.grpcserver.hookah.ProtoHookah}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.server.grpcserver.hookah.ProtoHookah)
      com.example.grpc.server.grpcserver.hookah.ProtoHookahOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.server.grpcserver.hookah.Hookah.internal_static_com_example_grpc_server_grpcserver_hookah_ProtoHookah_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.server.grpcserver.hookah.Hookah.internal_static_com_example_grpc_server_grpcserver_hookah_ProtoHookah_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.server.grpcserver.hookah.ProtoHookah.class, com.example.grpc.server.grpcserver.hookah.ProtoHookah.Builder.class);
    }

    // Construct using com.example.grpc.server.grpcserver.hookah.ProtoHookah.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      producer_ = "";

      material_ = "";

      size_ = "";

      price_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.server.grpcserver.hookah.Hookah.internal_static_com_example_grpc_server_grpcserver_hookah_ProtoHookah_descriptor;
    }

    public com.example.grpc.server.grpcserver.hookah.ProtoHookah getDefaultInstanceForType() {
      return com.example.grpc.server.grpcserver.hookah.ProtoHookah.getDefaultInstance();
    }

    public com.example.grpc.server.grpcserver.hookah.ProtoHookah build() {
      com.example.grpc.server.grpcserver.hookah.ProtoHookah result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.example.grpc.server.grpcserver.hookah.ProtoHookah buildPartial() {
      com.example.grpc.server.grpcserver.hookah.ProtoHookah result = new com.example.grpc.server.grpcserver.hookah.ProtoHookah(this);
      result.producer_ = producer_;
      result.material_ = material_;
      result.size_ = size_;
      result.price_ = price_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.server.grpcserver.hookah.ProtoHookah) {
        return mergeFrom((com.example.grpc.server.grpcserver.hookah.ProtoHookah)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.server.grpcserver.hookah.ProtoHookah other) {
      if (other == com.example.grpc.server.grpcserver.hookah.ProtoHookah.getDefaultInstance()) return this;
      if (!other.getProducer().isEmpty()) {
        producer_ = other.producer_;
        onChanged();
      }
      if (!other.getMaterial().isEmpty()) {
        material_ = other.material_;
        onChanged();
      }
      if (!other.getSize().isEmpty()) {
        size_ = other.size_;
        onChanged();
      }
      if (other.getPrice() != 0) {
        setPrice(other.getPrice());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.server.grpcserver.hookah.ProtoHookah parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.server.grpcserver.hookah.ProtoHookah) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object producer_ = "";
    /**
     * <code>string producer = 1;</code>
     */
    public java.lang.String getProducer() {
      java.lang.Object ref = producer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        producer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string producer = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProducerBytes() {
      java.lang.Object ref = producer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        producer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string producer = 1;</code>
     */
    public Builder setProducer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      producer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string producer = 1;</code>
     */
    public Builder clearProducer() {
      
      producer_ = getDefaultInstance().getProducer();
      onChanged();
      return this;
    }
    /**
     * <code>string producer = 1;</code>
     */
    public Builder setProducerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      producer_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object material_ = "";
    /**
     * <code>string material = 2;</code>
     */
    public java.lang.String getMaterial() {
      java.lang.Object ref = material_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        material_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string material = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMaterialBytes() {
      java.lang.Object ref = material_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        material_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string material = 2;</code>
     */
    public Builder setMaterial(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      material_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string material = 2;</code>
     */
    public Builder clearMaterial() {
      
      material_ = getDefaultInstance().getMaterial();
      onChanged();
      return this;
    }
    /**
     * <code>string material = 2;</code>
     */
    public Builder setMaterialBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      material_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object size_ = "";
    /**
     * <code>string size = 3;</code>
     */
    public java.lang.String getSize() {
      java.lang.Object ref = size_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        size_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string size = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSizeBytes() {
      java.lang.Object ref = size_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        size_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string size = 3;</code>
     */
    public Builder setSize(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string size = 3;</code>
     */
    public Builder clearSize() {
      
      size_ = getDefaultInstance().getSize();
      onChanged();
      return this;
    }
    /**
     * <code>string size = 3;</code>
     */
    public Builder setSizeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      size_ = value;
      onChanged();
      return this;
    }

    private int price_ ;
    /**
     * <code>int32 price = 4;</code>
     */
    public int getPrice() {
      return price_;
    }
    /**
     * <code>int32 price = 4;</code>
     */
    public Builder setPrice(int value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 price = 4;</code>
     */
    public Builder clearPrice() {
      
      price_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.server.grpcserver.hookah.ProtoHookah)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.server.grpcserver.hookah.ProtoHookah)
  private static final com.example.grpc.server.grpcserver.hookah.ProtoHookah DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.server.grpcserver.hookah.ProtoHookah();
  }

  public static com.example.grpc.server.grpcserver.hookah.ProtoHookah getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoHookah>
      PARSER = new com.google.protobuf.AbstractParser<ProtoHookah>() {
    public ProtoHookah parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoHookah(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoHookah> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoHookah> getParserForType() {
    return PARSER;
  }

  public com.example.grpc.server.grpcserver.hookah.ProtoHookah getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

