// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdatingBalance.proto

package com.example.grpc.server.grpcserver.updating;

public interface UpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.updating.UpdateResponse)
    com.google.protobuf.MessageOrBuilder {
}
