// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdatingBalance.proto

package com.example.grpc.server.grpcserver.updating;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.updating.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string paymentId = 1;</code>
   */
  java.lang.String getPaymentId();
  /**
   * <code>string paymentId = 1;</code>
   */
  com.google.protobuf.ByteString
      getPaymentIdBytes();

  /**
   * <code>int32 added_quantity = 2;</code>
   */
  int getAddedQuantity();
}
