// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tobakko.proto

package com.example.grpc.server.grpcserver.tobakko;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.tobakko.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakko = 1;</code>
   */
  boolean hasTobakko();
  /**
   * <code>.com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakko = 1;</code>
   */
  com.example.grpc.server.grpcserver.tobakko.ProtoTobakko getTobakko();
  /**
   * <code>.com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakko = 1;</code>
   */
  com.example.grpc.server.grpcserver.tobakko.ProtoTobakkoOrBuilder getTobakkoOrBuilder();
}
