// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tobakko.proto

package com.example.grpc.server.grpcserver.tobakko;

public interface DeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.tobakko.DeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tobakko_id = 1;</code>
   */
  java.lang.String getTobakkoId();
  /**
   * <code>string tobakko_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getTobakkoIdBytes();

  /**
   * <code>string payment_id = 2;</code>
   */
  java.lang.String getPaymentId();
  /**
   * <code>string payment_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getPaymentIdBytes();
}
