// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tobakko.proto

package com.example.grpc.server.grpcserver.tobakko;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.tobakko.GetRequest)
    com.google.protobuf.MessageOrBuilder {
}
