// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tobakko.proto

package com.example.grpc.server.grpcserver.tobakko;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.tobakko.GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
   */
  java.util.List<com.example.grpc.server.grpcserver.tobakko.ProtoTobakko> 
      getTobakkosList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
   */
  com.example.grpc.server.grpcserver.tobakko.ProtoTobakko getTobakkos(int index);
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
   */
  int getTobakkosCount();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
   */
  java.util.List<? extends com.example.grpc.server.grpcserver.tobakko.ProtoTobakkoOrBuilder> 
      getTobakkosOrBuilderList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.tobakko.ProtoTobakko tobakkos = 1;</code>
   */
  com.example.grpc.server.grpcserver.tobakko.ProtoTobakkoOrBuilder getTobakkosOrBuilder(
      int index);
}
