// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tobakko.proto

package com.example.grpc.server.grpcserver.tobakko;

public interface ProtoTobakkoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.tobakko.ProtoTobakko)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firm = 1;</code>
   */
  java.lang.String getFirm();
  /**
   * <code>string firm = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirmBytes();

  /**
   * <code>string taste = 2;</code>
   */
  java.lang.String getTaste();
  /**
   * <code>string taste = 2;</code>
   */
  com.google.protobuf.ByteString
      getTasteBytes();

  /**
   * <code>string strength = 3;</code>
   */
  java.lang.String getStrength();
  /**
   * <code>string strength = 3;</code>
   */
  com.google.protobuf.ByteString
      getStrengthBytes();

  /**
   * <code>int32 price = 4;</code>
   */
  int getPrice();
}
