// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tobakko.proto

package com.example.grpc.server.grpcserver.tobakko;

public final class Tobakko {
  private Tobakko() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_tobakko_ProtoTobakko_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_tobakko_ProtoTobakko_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_tobakko_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_tobakko_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_tobakko_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_tobakko_DeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_tobakko_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_tobakko_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_tobakko_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_tobakko_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_tobakko_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_tobakko_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_tobakko_CreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_tobakko_CreateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rTobakko.proto\022*com.example.grpc.server" +
      ".grpcserver.tobakko\"L\n\014ProtoTobakko\022\014\n\004f" +
      "irm\030\001 \001(\t\022\r\n\005taste\030\002 \001(\t\022\020\n\010strength\030\003 \001" +
      "(\t\022\r\n\005price\030\004 \001(\005\"7\n\rDeleteRequest\022\022\n\nto" +
      "bakko_id\030\001 \001(\t\022\022\n\npayment_id\030\002 \001(\t\" \n\016De" +
      "leteResponse\022\016\n\006report\030\001 \001(\t\"\014\n\nGetReque" +
      "st\"Y\n\013GetResponse\022J\n\010tobakkos\030\001 \003(\01328.co" +
      "m.example.grpc.server.grpcserver.tobakko" +
      ".ProtoTobakko\"Z\n\rCreateRequest\022I\n\007tobakk" +
      "o\030\001 \001(\01328.com.example.grpc.server.grpcse",
      "rver.tobakko.ProtoTobakko\"\034\n\016CreateRespo" +
      "nse\022\n\n\002id\030\001 \001(\t2\212\003\n\016TobakkoService\022v\n\003ge" +
      "t\0226.com.example.grpc.server.grpcserver.t" +
      "obakko.GetRequest\0327.com.example.grpc.ser" +
      "ver.grpcserver.tobakko.GetResponse\022\177\n\006de" +
      "lete\0229.com.example.grpc.server.grpcserve" +
      "r.tobakko.DeleteRequest\032:.com.example.gr" +
      "pc.server.grpcserver.tobakko.DeleteRespo" +
      "nse\022\177\n\006create\0229.com.example.grpc.server." +
      "grpcserver.tobakko.CreateRequest\032:.com.e",
      "xample.grpc.server.grpcserver.tobakko.Cr" +
      "eateResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_grpc_server_grpcserver_tobakko_ProtoTobakko_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_server_grpcserver_tobakko_ProtoTobakko_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_tobakko_ProtoTobakko_descriptor,
        new java.lang.String[] { "Firm", "Taste", "Strength", "Price", });
    internal_static_com_example_grpc_server_grpcserver_tobakko_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_server_grpcserver_tobakko_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_tobakko_DeleteRequest_descriptor,
        new java.lang.String[] { "TobakkoId", "PaymentId", });
    internal_static_com_example_grpc_server_grpcserver_tobakko_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_grpc_server_grpcserver_tobakko_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_tobakko_DeleteResponse_descriptor,
        new java.lang.String[] { "Report", });
    internal_static_com_example_grpc_server_grpcserver_tobakko_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_grpc_server_grpcserver_tobakko_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_tobakko_GetRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_example_grpc_server_grpcserver_tobakko_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_grpc_server_grpcserver_tobakko_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_tobakko_GetResponse_descriptor,
        new java.lang.String[] { "Tobakkos", });
    internal_static_com_example_grpc_server_grpcserver_tobakko_CreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_example_grpc_server_grpcserver_tobakko_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_tobakko_CreateRequest_descriptor,
        new java.lang.String[] { "Tobakko", });
    internal_static_com_example_grpc_server_grpcserver_tobakko_CreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_example_grpc_server_grpcserver_tobakko_CreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_tobakko_CreateResponse_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
