// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.example.grpc.server.grpcserver.employee;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.employee.GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
   */
  java.util.List<com.example.grpc.server.grpcserver.employee.ProtoEmployee> 
      getEmployeesList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
   */
  com.example.grpc.server.grpcserver.employee.ProtoEmployee getEmployees(int index);
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
   */
  int getEmployeesCount();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
   */
  java.util.List<? extends com.example.grpc.server.grpcserver.employee.ProtoEmployeeOrBuilder> 
      getEmployeesOrBuilderList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
   */
  com.example.grpc.server.grpcserver.employee.ProtoEmployeeOrBuilder getEmployeesOrBuilder(
      int index);
}
