// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.example.grpc.server.grpcserver.employee;

/**
 * Protobuf type {@code com.example.grpc.server.grpcserver.employee.GetResponse}
 */
public  final class GetResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.server.grpcserver.employee.GetResponse)
    GetResponseOrBuilder {
  // Use GetResponse.newBuilder() to construct.
  private GetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetResponse() {
    employees_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GetResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              employees_ = new java.util.ArrayList<com.example.grpc.server.grpcserver.employee.ProtoEmployee>();
              mutable_bitField0_ |= 0x00000001;
            }
            employees_.add(
                input.readMessage(com.example.grpc.server.grpcserver.employee.ProtoEmployee.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        employees_ = java.util.Collections.unmodifiableList(employees_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.server.grpcserver.employee.Employee.internal_static_com_example_grpc_server_grpcserver_employee_GetResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.server.grpcserver.employee.Employee.internal_static_com_example_grpc_server_grpcserver_employee_GetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.server.grpcserver.employee.GetResponse.class, com.example.grpc.server.grpcserver.employee.GetResponse.Builder.class);
  }

  public static final int EMPLOYEES_FIELD_NUMBER = 1;
  private java.util.List<com.example.grpc.server.grpcserver.employee.ProtoEmployee> employees_;
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
   */
  public java.util.List<com.example.grpc.server.grpcserver.employee.ProtoEmployee> getEmployeesList() {
    return employees_;
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
   */
  public java.util.List<? extends com.example.grpc.server.grpcserver.employee.ProtoEmployeeOrBuilder> 
      getEmployeesOrBuilderList() {
    return employees_;
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
   */
  public int getEmployeesCount() {
    return employees_.size();
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
   */
  public com.example.grpc.server.grpcserver.employee.ProtoEmployee getEmployees(int index) {
    return employees_.get(index);
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
   */
  public com.example.grpc.server.grpcserver.employee.ProtoEmployeeOrBuilder getEmployeesOrBuilder(
      int index) {
    return employees_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < employees_.size(); i++) {
      output.writeMessage(1, employees_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < employees_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, employees_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.server.grpcserver.employee.GetResponse)) {
      return super.equals(obj);
    }
    com.example.grpc.server.grpcserver.employee.GetResponse other = (com.example.grpc.server.grpcserver.employee.GetResponse) obj;

    boolean result = true;
    result = result && getEmployeesList()
        .equals(other.getEmployeesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEmployeesCount() > 0) {
      hash = (37 * hash) + EMPLOYEES_FIELD_NUMBER;
      hash = (53 * hash) + getEmployeesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.server.grpcserver.employee.GetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.employee.GetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.employee.GetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.employee.GetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.employee.GetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.employee.GetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.employee.GetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.employee.GetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.employee.GetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.employee.GetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.employee.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.employee.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.server.grpcserver.employee.GetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.server.grpcserver.employee.GetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.server.grpcserver.employee.GetResponse)
      com.example.grpc.server.grpcserver.employee.GetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.server.grpcserver.employee.Employee.internal_static_com_example_grpc_server_grpcserver_employee_GetResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.server.grpcserver.employee.Employee.internal_static_com_example_grpc_server_grpcserver_employee_GetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.server.grpcserver.employee.GetResponse.class, com.example.grpc.server.grpcserver.employee.GetResponse.Builder.class);
    }

    // Construct using com.example.grpc.server.grpcserver.employee.GetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEmployeesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (employeesBuilder_ == null) {
        employees_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        employeesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.server.grpcserver.employee.Employee.internal_static_com_example_grpc_server_grpcserver_employee_GetResponse_descriptor;
    }

    public com.example.grpc.server.grpcserver.employee.GetResponse getDefaultInstanceForType() {
      return com.example.grpc.server.grpcserver.employee.GetResponse.getDefaultInstance();
    }

    public com.example.grpc.server.grpcserver.employee.GetResponse build() {
      com.example.grpc.server.grpcserver.employee.GetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.example.grpc.server.grpcserver.employee.GetResponse buildPartial() {
      com.example.grpc.server.grpcserver.employee.GetResponse result = new com.example.grpc.server.grpcserver.employee.GetResponse(this);
      int from_bitField0_ = bitField0_;
      if (employeesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          employees_ = java.util.Collections.unmodifiableList(employees_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.employees_ = employees_;
      } else {
        result.employees_ = employeesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.server.grpcserver.employee.GetResponse) {
        return mergeFrom((com.example.grpc.server.grpcserver.employee.GetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.server.grpcserver.employee.GetResponse other) {
      if (other == com.example.grpc.server.grpcserver.employee.GetResponse.getDefaultInstance()) return this;
      if (employeesBuilder_ == null) {
        if (!other.employees_.isEmpty()) {
          if (employees_.isEmpty()) {
            employees_ = other.employees_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEmployeesIsMutable();
            employees_.addAll(other.employees_);
          }
          onChanged();
        }
      } else {
        if (!other.employees_.isEmpty()) {
          if (employeesBuilder_.isEmpty()) {
            employeesBuilder_.dispose();
            employeesBuilder_ = null;
            employees_ = other.employees_;
            bitField0_ = (bitField0_ & ~0x00000001);
            employeesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEmployeesFieldBuilder() : null;
          } else {
            employeesBuilder_.addAllMessages(other.employees_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.server.grpcserver.employee.GetResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.server.grpcserver.employee.GetResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.grpc.server.grpcserver.employee.ProtoEmployee> employees_ =
      java.util.Collections.emptyList();
    private void ensureEmployeesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        employees_ = new java.util.ArrayList<com.example.grpc.server.grpcserver.employee.ProtoEmployee>(employees_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.server.grpcserver.employee.ProtoEmployee, com.example.grpc.server.grpcserver.employee.ProtoEmployee.Builder, com.example.grpc.server.grpcserver.employee.ProtoEmployeeOrBuilder> employeesBuilder_;

    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public java.util.List<com.example.grpc.server.grpcserver.employee.ProtoEmployee> getEmployeesList() {
      if (employeesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(employees_);
      } else {
        return employeesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public int getEmployeesCount() {
      if (employeesBuilder_ == null) {
        return employees_.size();
      } else {
        return employeesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public com.example.grpc.server.grpcserver.employee.ProtoEmployee getEmployees(int index) {
      if (employeesBuilder_ == null) {
        return employees_.get(index);
      } else {
        return employeesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public Builder setEmployees(
        int index, com.example.grpc.server.grpcserver.employee.ProtoEmployee value) {
      if (employeesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeesIsMutable();
        employees_.set(index, value);
        onChanged();
      } else {
        employeesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public Builder setEmployees(
        int index, com.example.grpc.server.grpcserver.employee.ProtoEmployee.Builder builderForValue) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.set(index, builderForValue.build());
        onChanged();
      } else {
        employeesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public Builder addEmployees(com.example.grpc.server.grpcserver.employee.ProtoEmployee value) {
      if (employeesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeesIsMutable();
        employees_.add(value);
        onChanged();
      } else {
        employeesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public Builder addEmployees(
        int index, com.example.grpc.server.grpcserver.employee.ProtoEmployee value) {
      if (employeesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeesIsMutable();
        employees_.add(index, value);
        onChanged();
      } else {
        employeesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public Builder addEmployees(
        com.example.grpc.server.grpcserver.employee.ProtoEmployee.Builder builderForValue) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.add(builderForValue.build());
        onChanged();
      } else {
        employeesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public Builder addEmployees(
        int index, com.example.grpc.server.grpcserver.employee.ProtoEmployee.Builder builderForValue) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.add(index, builderForValue.build());
        onChanged();
      } else {
        employeesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public Builder addAllEmployees(
        java.lang.Iterable<? extends com.example.grpc.server.grpcserver.employee.ProtoEmployee> values) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, employees_);
        onChanged();
      } else {
        employeesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public Builder clearEmployees() {
      if (employeesBuilder_ == null) {
        employees_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        employeesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public Builder removeEmployees(int index) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.remove(index);
        onChanged();
      } else {
        employeesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public com.example.grpc.server.grpcserver.employee.ProtoEmployee.Builder getEmployeesBuilder(
        int index) {
      return getEmployeesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public com.example.grpc.server.grpcserver.employee.ProtoEmployeeOrBuilder getEmployeesOrBuilder(
        int index) {
      if (employeesBuilder_ == null) {
        return employees_.get(index);  } else {
        return employeesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public java.util.List<? extends com.example.grpc.server.grpcserver.employee.ProtoEmployeeOrBuilder> 
         getEmployeesOrBuilderList() {
      if (employeesBuilder_ != null) {
        return employeesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(employees_);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public com.example.grpc.server.grpcserver.employee.ProtoEmployee.Builder addEmployeesBuilder() {
      return getEmployeesFieldBuilder().addBuilder(
          com.example.grpc.server.grpcserver.employee.ProtoEmployee.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public com.example.grpc.server.grpcserver.employee.ProtoEmployee.Builder addEmployeesBuilder(
        int index) {
      return getEmployeesFieldBuilder().addBuilder(
          index, com.example.grpc.server.grpcserver.employee.ProtoEmployee.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.employee.ProtoEmployee employees = 1;</code>
     */
    public java.util.List<com.example.grpc.server.grpcserver.employee.ProtoEmployee.Builder> 
         getEmployeesBuilderList() {
      return getEmployeesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.server.grpcserver.employee.ProtoEmployee, com.example.grpc.server.grpcserver.employee.ProtoEmployee.Builder, com.example.grpc.server.grpcserver.employee.ProtoEmployeeOrBuilder> 
        getEmployeesFieldBuilder() {
      if (employeesBuilder_ == null) {
        employeesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.grpc.server.grpcserver.employee.ProtoEmployee, com.example.grpc.server.grpcserver.employee.ProtoEmployee.Builder, com.example.grpc.server.grpcserver.employee.ProtoEmployeeOrBuilder>(
                employees_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        employees_ = null;
      }
      return employeesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.server.grpcserver.employee.GetResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.server.grpcserver.employee.GetResponse)
  private static final com.example.grpc.server.grpcserver.employee.GetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.server.grpcserver.employee.GetResponse();
  }

  public static com.example.grpc.server.grpcserver.employee.GetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetResponse>() {
    public GetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetResponse> getParserForType() {
    return PARSER;
  }

  public com.example.grpc.server.grpcserver.employee.GetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

