// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.example.grpc.server.grpcserver.employee;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.employee.GetRequest)
    com.google.protobuf.MessageOrBuilder {
}
