// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.example.grpc.server.grpcserver.employee;

public interface ProtoEmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.employee.ProtoEmployee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string surname = 2;</code>
   */
  java.lang.String getSurname();
  /**
   * <code>string surname = 2;</code>
   */
  com.google.protobuf.ByteString
      getSurnameBytes();
}
