// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Payment.proto

package com.example.grpc.server.grpcserver.payment;

public interface DeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.payment.DeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string payment_id = 1;</code>
   */
  java.lang.String getPaymentId();
  /**
   * <code>string payment_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getPaymentIdBytes();
}
