// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Payment.proto

package com.example.grpc.server.grpcserver.payment;

/**
 * Protobuf type {@code com.example.grpc.server.grpcserver.payment.ProtoPayment}
 */
public  final class ProtoPayment extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.server.grpcserver.payment.ProtoPayment)
    ProtoPaymentOrBuilder {
  // Use ProtoPayment.newBuilder() to construct.
  private ProtoPayment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoPayment() {
    desk_ = 0;
    addedQuantity_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ProtoPayment(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            desk_ = input.readInt32();
            break;
          }
          case 16: {

            addedQuantity_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.server.grpcserver.payment.Payment.internal_static_com_example_grpc_server_grpcserver_payment_ProtoPayment_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.server.grpcserver.payment.Payment.internal_static_com_example_grpc_server_grpcserver_payment_ProtoPayment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.server.grpcserver.payment.ProtoPayment.class, com.example.grpc.server.grpcserver.payment.ProtoPayment.Builder.class);
  }

  public static final int DESK_FIELD_NUMBER = 1;
  private int desk_;
  /**
   * <code>int32 desk = 1;</code>
   */
  public int getDesk() {
    return desk_;
  }

  public static final int ADDED_QUANTITY_FIELD_NUMBER = 2;
  private int addedQuantity_;
  /**
   * <code>int32 added_quantity = 2;</code>
   */
  public int getAddedQuantity() {
    return addedQuantity_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (desk_ != 0) {
      output.writeInt32(1, desk_);
    }
    if (addedQuantity_ != 0) {
      output.writeInt32(2, addedQuantity_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (desk_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, desk_);
    }
    if (addedQuantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, addedQuantity_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.server.grpcserver.payment.ProtoPayment)) {
      return super.equals(obj);
    }
    com.example.grpc.server.grpcserver.payment.ProtoPayment other = (com.example.grpc.server.grpcserver.payment.ProtoPayment) obj;

    boolean result = true;
    result = result && (getDesk()
        == other.getDesk());
    result = result && (getAddedQuantity()
        == other.getAddedQuantity());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DESK_FIELD_NUMBER;
    hash = (53 * hash) + getDesk();
    hash = (37 * hash) + ADDED_QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getAddedQuantity();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.server.grpcserver.payment.ProtoPayment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.payment.ProtoPayment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.payment.ProtoPayment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.payment.ProtoPayment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.payment.ProtoPayment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.payment.ProtoPayment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.payment.ProtoPayment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.payment.ProtoPayment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.payment.ProtoPayment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.payment.ProtoPayment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.payment.ProtoPayment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.payment.ProtoPayment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.server.grpcserver.payment.ProtoPayment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.server.grpcserver.payment.ProtoPayment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.server.grpcserver.payment.ProtoPayment)
      com.example.grpc.server.grpcserver.payment.ProtoPaymentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.server.grpcserver.payment.Payment.internal_static_com_example_grpc_server_grpcserver_payment_ProtoPayment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.server.grpcserver.payment.Payment.internal_static_com_example_grpc_server_grpcserver_payment_ProtoPayment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.server.grpcserver.payment.ProtoPayment.class, com.example.grpc.server.grpcserver.payment.ProtoPayment.Builder.class);
    }

    // Construct using com.example.grpc.server.grpcserver.payment.ProtoPayment.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      desk_ = 0;

      addedQuantity_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.server.grpcserver.payment.Payment.internal_static_com_example_grpc_server_grpcserver_payment_ProtoPayment_descriptor;
    }

    public com.example.grpc.server.grpcserver.payment.ProtoPayment getDefaultInstanceForType() {
      return com.example.grpc.server.grpcserver.payment.ProtoPayment.getDefaultInstance();
    }

    public com.example.grpc.server.grpcserver.payment.ProtoPayment build() {
      com.example.grpc.server.grpcserver.payment.ProtoPayment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.example.grpc.server.grpcserver.payment.ProtoPayment buildPartial() {
      com.example.grpc.server.grpcserver.payment.ProtoPayment result = new com.example.grpc.server.grpcserver.payment.ProtoPayment(this);
      result.desk_ = desk_;
      result.addedQuantity_ = addedQuantity_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.server.grpcserver.payment.ProtoPayment) {
        return mergeFrom((com.example.grpc.server.grpcserver.payment.ProtoPayment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.server.grpcserver.payment.ProtoPayment other) {
      if (other == com.example.grpc.server.grpcserver.payment.ProtoPayment.getDefaultInstance()) return this;
      if (other.getDesk() != 0) {
        setDesk(other.getDesk());
      }
      if (other.getAddedQuantity() != 0) {
        setAddedQuantity(other.getAddedQuantity());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.server.grpcserver.payment.ProtoPayment parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.server.grpcserver.payment.ProtoPayment) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int desk_ ;
    /**
     * <code>int32 desk = 1;</code>
     */
    public int getDesk() {
      return desk_;
    }
    /**
     * <code>int32 desk = 1;</code>
     */
    public Builder setDesk(int value) {
      
      desk_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 desk = 1;</code>
     */
    public Builder clearDesk() {
      
      desk_ = 0;
      onChanged();
      return this;
    }

    private int addedQuantity_ ;
    /**
     * <code>int32 added_quantity = 2;</code>
     */
    public int getAddedQuantity() {
      return addedQuantity_;
    }
    /**
     * <code>int32 added_quantity = 2;</code>
     */
    public Builder setAddedQuantity(int value) {
      
      addedQuantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 added_quantity = 2;</code>
     */
    public Builder clearAddedQuantity() {
      
      addedQuantity_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.server.grpcserver.payment.ProtoPayment)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.server.grpcserver.payment.ProtoPayment)
  private static final com.example.grpc.server.grpcserver.payment.ProtoPayment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.server.grpcserver.payment.ProtoPayment();
  }

  public static com.example.grpc.server.grpcserver.payment.ProtoPayment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoPayment>
      PARSER = new com.google.protobuf.AbstractParser<ProtoPayment>() {
    public ProtoPayment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoPayment(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoPayment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoPayment> getParserForType() {
    return PARSER;
  }

  public com.example.grpc.server.grpcserver.payment.ProtoPayment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

