// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Payment.proto

package com.example.grpc.server.grpcserver.payment;

public interface ProtoPaymentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.payment.ProtoPayment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 desk = 1;</code>
   */
  int getDesk();

  /**
   * <code>int32 added_quantity = 2;</code>
   */
  int getAddedQuantity();
}
