// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Payment.proto

package com.example.grpc.server.grpcserver.payment;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.payment.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.grpc.server.grpcserver.payment.ProtoPayment payment = 1;</code>
   */
  boolean hasPayment();
  /**
   * <code>.com.example.grpc.server.grpcserver.payment.ProtoPayment payment = 1;</code>
   */
  com.example.grpc.server.grpcserver.payment.ProtoPayment getPayment();
  /**
   * <code>.com.example.grpc.server.grpcserver.payment.ProtoPayment payment = 1;</code>
   */
  com.example.grpc.server.grpcserver.payment.ProtoPaymentOrBuilder getPaymentOrBuilder();
}
