// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Payment.proto

package com.example.grpc.server.grpcserver.payment;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.payment.GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.grpc.server.grpcserver.payment.ProtoPayment payments = 1;</code>
   */
  java.util.List<com.example.grpc.server.grpcserver.payment.ProtoPayment> 
      getPaymentsList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.payment.ProtoPayment payments = 1;</code>
   */
  com.example.grpc.server.grpcserver.payment.ProtoPayment getPayments(int index);
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.payment.ProtoPayment payments = 1;</code>
   */
  int getPaymentsCount();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.payment.ProtoPayment payments = 1;</code>
   */
  java.util.List<? extends com.example.grpc.server.grpcserver.payment.ProtoPaymentOrBuilder> 
      getPaymentsOrBuilderList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.payment.ProtoPayment payments = 1;</code>
   */
  com.example.grpc.server.grpcserver.payment.ProtoPaymentOrBuilder getPaymentsOrBuilder(
      int index);
}
